version: '3'
services:
  stock_insight_app:
    build:
      context: ./stock_insight_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - fundamental_analysis_service
      - technical_analysis_service
      - predictive_analysis_service

  fundamental_analysis_service:
    build:
      context: ./microservices/fundamental_analysis_service
    ports:
      - "5003:5003"

  technical_analysis_service:
    build:
      context: ./microservices/technical_analysis_service
    ports:
      - "5001:5001"

  predictive_analysis_service:
    build:
      context: ./microservices/predictive_analysis_service
    ports:
      - "5008:5008"

  scraping_service:
    build:
      context: ./microservices/scraping_service
    ports:
      - "5010:5010"

